
set(SOURCE_FILE ${CMAKE_ARGV3})
set(HEADER_FILE ${CMAKE_ARGV4})

cmake_path(GET SOURCE_FILE FILENAME FILE_NAME)
string(REPLACE "." "_" SHADER_NAME ${FILE_NAME})
string(TOUPPER ${SHADER_NAME} VARIABLE_NAME)

FILE(READ ${SOURCE_FILE} LINE_CONTENTS)
STRING(REGEX REPLACE ";" "{{SEMICOLON}}" LINE_CONTENTS "${LINE_CONTENTS}")
STRING(REGEX REPLACE "\n" ";" LINE_CONTENTS "${LINE_CONTENTS}")

foreach(LINE IN LISTS LINE_CONTENTS)
    string(CONCAT CONTENTS "${CONTENTS}" "R\"(${LINE}\n)\" ")
endforeach()

STRING(REGEX REPLACE "{{SEMICOLON}}" ";" CONTENTS "${CONTENTS}")

get_filename_component(OUTPUT_DIR ${HEADER_FILE} DIRECTORY)
make_directory(${OUTPUT_DIR})
FILE(WRITE ${HEADER_FILE} "#pragma once\n\n#include <string_view>\n\nconstexpr std::string_view ${VARIABLE_NAME} = {\n${CONTENTS}\n};\n")
